name: Task Manager CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [17, 21]

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.java-version}}
          distribution: 'temurin'
          cache: maven

      - name: Build and test application
        run: mvn clean package
        
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: task-manager-java-${{matrix.java-version}}
          path: target/task-manager.jar

  verify-artifact:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Downlaod Artifact
        uses: actions/download-artifact@v4
        with:
          name: task-manager-java-17

      - name: Display downloaded files
        run: ls -R

  information:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Display pipeline information
        run: |
          echo "Repository : ${{ github.repository }}"
          echo "Branch     : ${{github.ref_name}}"
          echo "Commit     : ${{github.sha}}"
          echo "Actor       : ${{github.actor}}"
  package:
    needs: verify-artifact
    runs-on: ubuntu-latest
    steps:
      - name: Downlaod application
        uses: actions/download-artifact@v4
        with:
          name: task-manager-jar

      - name: Display package content
        run: | 
          echo "Package application..."
          ls -lh
